mavoltl( ...
	'assr_label','TESTPROJ-x-TESTSUBJ-x-TESTSESS-x-TESTSCAN-x-Temporal_Lobe_v3', ...
	'seg_niigz','../INPUTS/T1_seg.nii.gz', ...
	'vol_txt','../INPUTS/T1_label_volumes.txt', ...
	'out_dir','../OUTPUTS' ...
	);
